export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR =  'AGREGAR_USUARIO_ERROR';
//Productos
export const COMENZAR_DESCARGA_USUARIOS  = 'COMENZAR_DESCARGA_USUARIOS';
export const DESCARGA_USUARIO_EXITO = 'DESCARGA_USUARIO_EXITO';
export const DESCARGA_USUARIO_ERROR = 'DESCARGA_USUARIO_ERROR';
//Eliminar
export const OBTENER_USUARIO_ELIMINAR = 'OBTENER_USUARIO_ELIMINAR';
export const USUARIO_ELIMINAR_EXITO = 'USUARIO_ELIMINAR_EXITO';
export const USUARIO_ELIMINAR_ERROR = 'USUARIO_ELIMINAR_ERROR';
//Editar
export const OBTENER_USUARIO_EDITAR = 'OBTENER_USUARIO_EDITAR';
export const COMENZAR_EDICION_USUARIO = 'COMENZAR_EDICION_USUARIO';
export const USUARIO_EDITAR_EXITO = 'PRODUCTO_EDITAR_EXITO ';
export const USUARIO_EDITAR_ERROR = 'PRODUCTO_EDITAR_ERROR';
//Alerta
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';