export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';
export const AGREGAR_USUARIO_EXITO = 'AGREGAR_USUARIO_EXITO';
export const AGREGAR_USUARIO_ERROR =  'AGREGAR_USUARIO_ERROR';
//Productos
export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';
//Eliminar
export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINAR_EXITO = 'PRODUCTO_ELIMINAR_EXITO';
export const PRODUCTO_ELIMINAR_ERROR = 'PRODUCTO_ELIMINAR_ERROR';
//Editar
export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR';
export const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO';
export const PRODUCTO_EDITAR_EXITO = 'PRODUCTO_EDITAR_EXITO ';
export const PRODUCTO_EDITAR_ERROR = 'PRODUCTO_EDITAR_ERROR';
//Alerta
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';